prompt_1:
  attention_hook: "none"
  task_description: "none"
  input_data: "none"
  processing_data: "none"
  context_intro: "none"
  task_context: "none"
  question: "default"
  answer_options: "default"
  solution_motivation: "none"
  reasoning_motivation: "none"
  reasoning_format: "none"
  answer_format: "informal_technical"
  limitations: "none"
  answer_motivation: "none"

prompt_2:
  attention_hook: "none"
  task_description: "formal_request"
  input_data: "default"
  processing_data: "none"
  context_intro: "none"
  task_context: "none"
  question: "default"
  answer_options: "default"
  solution_motivation: "none"
  reasoning_motivation: "none"
  reasoning_format: "none"
  answer_format: "formal_request"
  limitations: "none"
  answer_motivation: "none"

prompt_3:
  attention_hook: "none"
  task_description: "none"
  input_data: "none"
  processing_data: "none"
  context_intro: "in_dataset"
  task_context: "default"
  question: "default"
  answer_options: "default"
  solution_motivation: "formal_request"
  reasoning_motivation: "none"
  reasoning_format: "none"
  answer_format: "formal_request"
  limitations: "none"
  answer_motivation: "none"

prompt_4:
  attention_hook: "none"
  task_description: "informal_request"
  input_data: "default"
  processing_data: "informal_request"
  context_intro: "in_dataset"
  task_context: "default"
  question: "default"
  answer_options: "default"
  solution_motivation: "informal_request"
  reasoning_motivation: "none"
  reasoning_format: "none"
  answer_format: "informal_request"
  limitations: "informal_request"
  answer_motivation: "none"

prompt_5:
  attention_hook: "none"
  task_description: "formal_wish"
  input_data: "default"
  processing_data: "formal_wish"
  context_intro: "none"
  task_context: "none"
  question: "default"
  answer_options: "default"
  solution_motivation: "none"
  reasoning_motivation: "none"
  reasoning_format: "none"
  answer_format: "formal_wish"
  limitations: "none"
  answer_motivation: "none"

prompt_6:
  attention_hook: "none"
  task_description: "informal_order"
  input_data: "default"
  processing_data: "none"
  context_intro: "none"
  task_context: "none"
  question: "default"
  answer_options: "default"
  solution_motivation: "none"
  reasoning_motivation: "none"
  reasoning_format: "none"
  answer_format: "informal_order"
  limitations: "informal_order"
  answer_motivation: "none"

prompt_7:
  attention_hook: "none"
  task_description: "none"
  input_data: "none"
  processing_data: "none"
  context_intro: "in_dataset"
  task_context: "default"
  question: "default"
  answer_options: "default"
  solution_motivation: "impersonal_order"
  reasoning_motivation: "none"
  reasoning_format: "none"
  answer_format: "impersonal_order"
  limitations: "impersonal_order"
  answer_motivation: "none"

prompt_8:
  attention_hook: "none"
  task_description: "impersonal_fact"
  input_data: "default"
  processing_data: "none"
  context_intro: "none"
  task_context: "none"
  question: "default"
  answer_options: "default"
  solution_motivation: "none"
  reasoning_motivation: "none"
  reasoning_format: "none"
  answer_format: "impersonal_fact"
  limitations: "none"
  answer_motivation: "none"

prompt_9:
  attention_hook: "none"
  task_description: "impersonal_request"
  input_data: "default"
  processing_data: "impersonal_request"
  context_intro: "in_dataset"
  task_context: "default"
  question: "default"
  answer_options: "default"
  solution_motivation: "none"
  reasoning_motivation: "none"
  reasoning_format: "none"
  answer_format: "impersonal_request"
  limitations: "impersonal_request"
  answer_motivation: "none"

prompt_10:
  attention_hook: "none"
  task_description: "none"
  input_data: "default"
  processing_data: "informal_technical"
  context_intro: "none"
  task_context: "none"
  question: "default"
  answer_options: "default"
  solution_motivation: "informal_technical"
  reasoning_motivation: "none"
  reasoning_format: "none"
  answer_format: "informal_technical"
  limitations: "none"
  answer_motivation: "none"
